### ISSUE TITLE
Introduce `IQueryPreProcessor` support

### ISSUE THREAD

**Issue by SebastianKuesters** [wemogy/libs-cqrs#51]
As a developer I want to have the option to define a `IQueryPreProcessor` for my query.
This could be useful in the following sample:

Given is the following query:

```csharp
public class GetSharedLinkPermissionsQuery : IQuery<GetSharedLinkPermissionsQueryResult>
  {
      public Guid? SharedLinkId { get; set; }

      public SharedLink? SharedLink { get; set; }

      public GetSharedLinkPermissionsQuery(Guid sharedLinkId)
      {
          SharedLinkId = sharedLinkId;
      }

      public GetSharedLinkPermissionsQuery(SharedLink sharedLink)
      {
          SharedLink = sharedLink;
      }
  }
```

For this I would like to add a PreProcessor, which requests the `SharedLink` entity from the database, if the constructor with the `Guid` parameter was used.
Using this I can ensure, that in the `IQueryHandler` implementation both properties are always set, so that I can focus on the Core logic.

**Comment by SebastianKuesters** [comment]
@robinmanuelthiel pls give me feedback on this feature request.

**Comment by robinmanuelthiel** [comment]
We should come up with written down rules and best-practises on how we write and sctructure Queries (and Commands) across our projects!

**Comment by robinmanuelthiel** [comment]
Documented https://github.com/wemogy/libs-cqrs/pull/52
